openapi: 3.0.0
info:
  title: SpendSync Analytics Service API
  version: 1.0.0
  description: |
    API documentation for the SpendSync Analytics Service.
    This service provides analytics and insights for user spending patterns.

servers:
  - url: /api/v1
    description: Production server
  - url: http://localhost:3005/api/v1
    description: Development server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: object
          properties:
            code:
              type: string
              example: VALIDATION_ERROR
            message:
              type: string
              example: Validation failed
            details:
              type: array
              items:
                type: object
                properties:
                  field:
                    type: string
                  message:
                    type: string

    AnalyticsEvent:
      type: object
      required:
        - userId
        - timestamp
        - eventName
        - deviceInfo
      properties:
        userId:
          type: string
          example: user123
        timestamp:
          type: string
          format: date-time
        eventName:
          type: string
          example: purchase_completed
        metadata:
          type: object
          example:
            category: food
            amount: 50.25
        deviceInfo:
          type: object
          required:
            - platform
            - version
          properties:
            platform:
              type: string
              enum: [ios, android, web]
            version:
              type: string
            model:
              type: string
            osVersion:
              type: string

    BatchEvents:
      type: object
      required:
        - events
      properties:
        events:
          type: array
          items:
            $ref: '#/components/schemas/AnalyticsEvent'
          maxItems: 100

    AnalyticsQuery:
      type: object
      required:
        - startDate
        - endDate
      properties:
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        userId:
          type: string
        eventName:
          type: string
        platform:
          type: string
          enum: [ios, android, web]
        limit:
          type: integer
          minimum: 1
          maximum: 1000
          default: 100
        offset:
          type: integer
          minimum: 0
          default: 0
        sort:
          type: string
          enum: [asc, desc]
          default: desc

paths:
  /analytics/track:
    post:
      summary: Track a single analytics event
      tags: [Analytics]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnalyticsEvent'
      responses:
        '201':
          description: Event tracked successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/AnalyticsEvent'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '413':
          description: Payload too large
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /analytics/batch:
    post:
      summary: Track multiple analytics events in batch
      tags: [Analytics]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchEvents'
      responses:
        '201':
          description: Events tracked successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      processedCount:
                        type: integer
                      results:
                        type: array
                        items:
                          $ref: '#/components/schemas/AnalyticsEvent'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '413':
          description: Payload too large
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /analytics/query:
    get:
      summary: Query analytics events
      tags: [Analytics]
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: startDate
          required: true
          schema:
            type: string
            format: date-time
        - in: query
          name: endDate
          required: true
          schema:
            type: string
            format: date-time
        - in: query
          name: userId
          schema:
            type: string
        - in: query
          name: eventName
          schema:
            type: string
        - in: query
          name: platform
          schema:
            type: string
            enum: [ios, android, web]
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 1000
            default: 100
        - in: query
          name: offset
          schema:
            type: integer
            minimum: 0
            default: 0
        - in: query
          name: sort
          schema:
            type: string
            enum: [asc, desc]
            default: desc
      responses:
        '200':
          description: Query results
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      total:
                        type: integer
                      offset:
                        type: integer
                      limit:
                        type: integer
                      results:
                        type: array
                        items:
                          $ref: '#/components/schemas/AnalyticsEvent'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /metrics:
    get:
      summary: Get service metrics
      tags: [Monitoring]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Prometheus metrics
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Error generating metrics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /health:
    get:
      summary: Service health check
      tags: [Monitoring]
      responses:
        '200':
          description: Service status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: UP
                  service:
                    type: string
                    example: analytics-service
                  timestamp:
                    type: string
                    format: date-time 