version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: spendsync-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: spendsync
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - spendsync-network

  # Redis Cache
  redis:
    image: redis:7.2-alpine
    container_name: spendsync-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - spendsync-network

  # API Gateway
  api-gateway:
    build:
      context: .
      dockerfile: docker/Dockerfile.gateway
    container_name: spendsync-api-gateway
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/spendsync?authSource=admin
      - REDIS_URL=redis://redis:6379
      - USER_SERVICE_URL=http://user-service:3001
      - EXPENSE_SERVICE_URL=http://expense-service:3002
      - SETTLEMENT_SERVICE_URL=http://settlement-service:3003
      - NOTIFICATION_SERVICE_URL=http://notification-service:3004
      - PAYMENT_SERVICE_URL=http://payment-service:3005
      - ANALYTICS_SERVICE_URL=http://analytics-service:3006
    depends_on:
      - mongodb
      - redis
      - user-service
      - expense-service
      - settlement-service
      - notification-service
      - payment-service
      - analytics-service
    networks:
      - spendsync-network
    volumes:
      - ./logs:/app/logs

  # User Service
  user-service:
    build:
      context: .
      dockerfile: docker/Dockerfile.user
    container_name: spendsync-user-service
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/spendsync?authSource=admin
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    networks:
      - spendsync-network

  # Expense Service
  expense-service:
    build:
      context: .
      dockerfile: docker/Dockerfile.expense
    container_name: spendsync-expense-service
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/spendsync?authSource=admin
      - REDIS_URL=redis://redis:6379
      - USER_SERVICE_URL=http://user-service:3001
    depends_on:
      - mongodb
      - redis
      - user-service
    networks:
      - spendsync-network

  # Settlement Service
  settlement-service:
    build:
      context: .
      dockerfile: docker/Dockerfile.settlement
    container_name: spendsync-settlement-service
    restart: unless-stopped
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/spendsync?authSource=admin
      - REDIS_URL=redis://redis:6379
      - USER_SERVICE_URL=http://user-service:3001
      - EXPENSE_SERVICE_URL=http://expense-service:3002
    depends_on:
      - mongodb
      - redis
      - user-service
      - expense-service
    networks:
      - spendsync-network

  # Notification Service
  notification-service:
    build:
      context: .
      dockerfile: docker/Dockerfile.notification
    container_name: spendsync-notification-service
    restart: unless-stopped
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - PORT=3004
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/spendsync?authSource=admin
      - REDIS_URL=redis://redis:6379
      - EMAIL_SERVICE_API_KEY=${EMAIL_SERVICE_API_KEY}
      - SMS_SERVICE_API_KEY=${SMS_SERVICE_API_KEY}
    depends_on:
      - mongodb
      - redis
    networks:
      - spendsync-network

  # Payment Service
  payment-service:
    build:
      context: .
      dockerfile: docker/Dockerfile.payment
    container_name: spendsync-payment-service
    restart: unless-stopped
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
      - PORT=3005
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/spendsync?authSource=admin
      - REDIS_URL=redis://redis:6379
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - PLAID_CLIENT_ID=${PLAID_CLIENT_ID}
      - PLAID_SECRET=${PLAID_SECRET}
      - PLAID_ENV=${PLAID_ENV:-sandbox}
    depends_on:
      - mongodb
      - redis
    networks:
      - spendsync-network

  # Analytics Service
  analytics-service:
    build:
      context: .
      dockerfile: docker/Dockerfile.analytics
    container_name: spendsync-analytics-service
    restart: unless-stopped
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=development
      - PORT=3006
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/spendsync?authSource=admin
      - REDIS_URL=redis://redis:6379
      - USER_SERVICE_URL=http://user-service:3001
      - EXPENSE_SERVICE_URL=http://expense-service:3002
      - SETTLEMENT_SERVICE_URL=http://settlement-service:3003
    depends_on:
      - mongodb
      - redis
      - user-service
      - expense-service
      - settlement-service
    networks:
      - spendsync-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  spendsync-network:
    driver: bridge 