version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: spendsync-mongodb-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: spendsync_dev
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - spendsync-dev-network

  # Redis Cache
  redis:
    image: redis:7.2-alpine
    container_name: spendsync-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - spendsync-dev-network

  # API Gateway
  api-gateway:
    build:
      context: .
      dockerfile: docker/Dockerfile.gateway
      target: development
    container_name: spendsync-api-gateway-dev
    restart: unless-stopped
    ports:
      - "4000:4000"
      - "9229:9229"  # Debug port
    environment:
      - NODE_ENV=development
      - PORT=4000
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/spendsync_dev?authSource=admin
      - REDIS_URL=redis://redis:6379
      - USER_SERVICE_URL=http://user-service:3001
      - EXPENSE_SERVICE_URL=http://expense-service:3002
      - SETTLEMENT_SERVICE_URL=http://settlement-service:3003
      - NOTIFICATION_SERVICE_URL=http://notification-service:3004
      - PAYMENT_SERVICE_URL=http://payment-service:3005
      - ANALYTICS_SERVICE_URL=http://analytics-service:3006
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
    depends_on:
      - mongodb
      - redis
    networks:
      - spendsync-dev-network

  # User Service
  user-service:
    build:
      context: .
      dockerfile: docker/Dockerfile.user
      target: development
    container_name: spendsync-user-service-dev
    restart: unless-stopped
    ports:
      - "3001:3001"
      - "9230:9229"  # Debug port
    environment:
      - NODE_ENV=development
      - PORT=3001
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/spendsync_dev?authSource=admin
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./src/services/user-service:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - redis
    networks:
      - spendsync-dev-network

volumes:
  mongodb_dev_data:
    driver: local
  redis_dev_data:
    driver: local

networks:
  spendsync-dev-network:
    driver: bridge 