version: '3.8'

services:
  pact-tests:
    platform: linux/amd64
    build:
      context: .
      dockerfile: docker/pact-arm64.Dockerfile
    volumes:
      - ./pacts:/app/pacts
      - ./logs:/app/logs
    environment:
      - NODE_ENV=test
    ports:
      - "1234:1234" # For Pact mock server
    # Use a custom command to run specific tests
    command: npm run test:contract 