apiVersion: v1
kind: ConfigMap
metadata:
  name: api-key-service-config
  namespace: spendsync
data:
  # API Key Service Configuration
  API_KEY_DB_NAME: "spendsync"
  API_KEY_COLLECTION: "apiKeys"
  API_KEY_RETENTION_DAYS: "365"
  API_KEY_ROTATION_GRACE_DAYS: "7"
  API_KEY_PREFIX: "sk_"

  # Rate Limiting
  RATE_LIMIT_WINDOW: "3600"  # 1 hour in seconds
  RATE_LIMIT_MAX_REQUESTS: "1000"
  RATE_LIMIT_KEY_GEN: "10"   # per hour
  RATE_LIMIT_KEY_ROTATION: "5"  # per hour

  # Security Settings
  ALLOWED_IPS: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"  # Internal networks
  MAX_KEY_AGE_DAYS: "365"
  MIN_KEY_LENGTH: "32"
  
  # Audit Logging
  AUDIT_DB_NAME: "audit_logs"
  AUDIT_RETENTION_DAYS: "90"
  AUDIT_BATCH_SIZE: "1000"
  
  # Metrics
  METRICS_PREFIX: "spendsync_api_key"
  METRICS_INTERVAL: "15"  # seconds

  # Alert Configuration
  ALERT_THRESHOLD_FAILED_ATTEMPTS: "5"
  ALERT_THRESHOLD_API_ERRORS: "10"
  ALERT_THRESHOLD_SUSPICIOUS_IPS: "3" 