apiVersion: v1
kind: ConfigMap
metadata:
  name: api-key-service-nginx-config
  namespace: spendsync
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log warn;
    pid /var/run/nginx.pid;

    events {
      worker_connections 1024;
    }

    http {
      include /etc/nginx/mime.types;
      default_type application/octet-stream;

      # Logging
      log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
      access_log /var/log/nginx/access.log main;

      # Security headers
      add_header X-Frame-Options "DENY" always;
      add_header X-Content-Type-Options "nosniff" always;
      add_header X-XSS-Protection "1; mode=block" always;
      add_header Content-Security-Policy "default-src 'none'; frame-ancestors 'none'" always;
      add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
      add_header Referrer-Policy "strict-origin-when-cross-origin" always;
      add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;

      # Rate limiting zones
      limit_req_zone $binary_remote_addr zone=api_key_limit:10m rate=10r/s;
      limit_req_zone $binary_remote_addr zone=api_key_gen:10m rate=1r/m;
      limit_req_zone $binary_remote_addr zone=api_key_rotation:10m rate=5r/h;

      # IP whitelist
      geo $internal_ip {
        default 0;
        10.0.0.0/8 1;
        172.16.0.0/12 1;
        192.168.0.0/16 1;
      }

      server {
        listen 80;
        server_name _;

        # Health check endpoint
        location /health {
          access_log off;
          return 200 "healthy\n";
        }

        # API key generation
        location /api/keys {
          limit_req zone=api_key_gen burst=5 nodelay;
          limit_except POST { deny all; }
          
          proxy_pass http://localhost:3000;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }

        # API key rotation
        location /api/keys/rotate {
          limit_req zone=api_key_rotation burst=10 nodelay;
          limit_except POST { deny all; }
          
          proxy_pass http://localhost:3000;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }

        # General API endpoints
        location /api/ {
          limit_req zone=api_key_limit burst=20 nodelay;
          
          # IP restrictions for sensitive operations
          if ($request_method = DELETE) {
            set $restricted 1;
          }
          if ($internal_ip = 0) {
            set $restricted "${restricted}1";
          }
          if ($restricted = 11) {
            return 403 "Access denied\n";
          }

          proxy_pass http://localhost:3000;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          
          # Request size limits
          client_max_body_size 10k;
          client_body_timeout 10s;
          
          # Response timeouts
          proxy_connect_timeout 60s;
          proxy_send_timeout 60s;
          proxy_read_timeout 60s;
        }

        # Deny access to all other paths
        location / {
          deny all;
        }
      }
    } 