apiVersion: v1
kind: ResourceQuota
metadata:
  name: api-key-service-quota
  namespace: spendsync
spec:
  hard:
    # Pod limits
    pods: "10"
    
    # CPU limits
    requests.cpu: "2"
    limits.cpu: "4"
    
    # Memory limits
    requests.memory: "4Gi"
    limits.memory: "8Gi"
    
    # Storage limits
    requests.storage: "10Gi"
    persistentvolumeclaims: "5"
    
    # ConfigMaps and Secrets
    configmaps: "10"
    secrets: "10"
    
    # Services
    services: "5"
    services.loadbalancers: "1"
    services.nodeports: "2"
    
    # Other resources
    replicationcontrollers: "5"
    deployments.apps: "5" 